# CloudFormartion Template


## Resources

- [AWS Docs - Template Anatomy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html)
  - [Metadata](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html)
  - [Parameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html)
  - [Rules](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/rules-section-structure.html)
  - [Mappings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html)
  - [Conditions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html)
  - [Transform](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html)
  - [Resources](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html)
  - [Outputs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html)
- [The AWS CloudFormation Fundamentals Series](https://www.youtube.com/watch?v=VgrJDdJhtps&list=PLesRB-DxZa8YOPvZm5RbMS_61EeA-xMKK&index=1)
  - Workflow: Find the resource you want, pick the properties, add it to the template 


------------
## YAML Template
------------
# Filename: 
# Version: 
# stack-name: 

AWSTemplateFormatVersion: "2010-09-09"

###########################################################################
# Section: Description
###########################################################################
Description: >
  Details about the template here.

###########################################################################
# Section: Metadata
###########################################################################
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    -
      Label:
        default: "Environment"
      Parameters:
        - Environment
    -
      Label:
        default: "Parameter2"
      Parameters:
        - Parameter2
    
    ParameterLabels:
      Environment:
        default: "The environment where the VPC will be created"
      Parameter2:
        default: "Default description"
        
###########################################################################
# Section: Parameters
###########################################################################        
Parameters:
  Environment:
    Description: "Environment"
    Type: String
    ConstraintDescription: "Must be in the set of allowed values"
    Default: staging
    AllowedValues:
      - staging
      - production
      - management
  
  Parameter2:
    Description: "Environment"
    Type: String
    ConstraintDescription: "Must be in the set of allowed values"
    Default: staging
    AllowedValues:
      - staging

###########################################################################
# Section: Conditions
##########################################################################
Conditions:
  LogicalId:
    Intrinsic function
    
###########################################################################
# Section: Mappings
###########################################################################
Mappings:
  NameofMap: 
    Key01: 
      Name: Value01
    Key02: 
      Name: Value02
    Key03: 
      Name: Value03
      
###########################################################################
# Section: Transform
###########################################################################
Transform:
  set of transforms

###########################################################################
# Section: Resources
###########################################################################
Resources:
  LogicalId:
    Type: "AWS::Cloud9::EnvironmentEC2"
    Properties:
      PropertyName: Value

  #############################################################################
  ##### SUB-SECTION HEADER #####
  #############################################################################

  ## Item A ##
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      Tags:
      - Key: 
        Value: 

  ## Item B ##
  ...

  ################### Section/Group A ###############
  
   ################### Section/Group B ###############


###########################################################################
# Section: Outputs
###########################################################################
Outputs:
  Logical ID:
    Description: Information about the value
    Value: Value to return
    Export:
      Name: 
        Fn::Sub: ${AWS::StackName}-SecurityGroupId
  
  ## Item/Group ##
