# CloudFormartion Template

------------
## Resources
------------

- [AWS Docs - Template Anatomy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html)
  - [Metadata](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html)
  - [Parameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html)
  - [Rules](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/rules-section-structure.html)
  - [Mappings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html)
  - [Conditions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html)
  - [Transform](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html)
  - [Resources](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html)
  - [Outputs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html)
- [The AWS CloudFormation Fundamentals Series](https://www.youtube.com/watch?v=VgrJDdJhtps&list=PLesRB-DxZa8YOPvZm5RbMS_61EeA-xMKK&index=1)
  - Workflow: Find the resource you want, pick the properties, add it to the template 


------------
## Template
------------

AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Details about the template here.

Metadata: 
  Instances:
    Description: "Information about the instances"
  Databases: 
    Description: "Information about the databases"

Parameters: 
  ParamLogicalId:
    Type: DataType "String"
    Description:
    ParameterProperty: value

Mappings:
  NameofMap: 
    Key01: 
      Name: Value01
    Key02: 
      Name: Value02
    Key03: 
      Name: Value03

Conditions:
  LogicalId:
    Intrinsic function

Transform:
  set of transforms

Resources:
  LogicalId:
    Type: "AWS::Cloud9::EnvironmentEC2"
    Properties:
      PropertyName: Value

Outputs:
  Logical ID:
    Description: Information about the value
    Value: Value to return
    Export:
      Name: 
        Fn::Sub: ${AWS::StackName}-SecurityGroupId
